---
- name: Converge
  hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - name: "Converge OpenVPN"
      ansible.builtin.debug:
        msg: "Executing OpenVPN config..."
  roles:
    - openvpn