galaxy_info:
  role_name: grafana
  namespace: itmoment
  author: alexander
  description: Install and configure Grafana monitoring tool
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
